#!/bin/bash

source "${CONTAINER_SCRIPTS_PATH}/common.sh"

generate_passwd_file

ansible-playbook -c local -i localhost, /var/lib/pgsql/entrypoint.yml -e etcd=example-etcd-cluster.psql-ha-poc.svc


exec patroni /var/lib/pgsql/postgres.yml
